apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/job-scheduler-node-network: "true"
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
            - name: MYSQL_DATABASE
              value: job-scheduler
            - name: MYSQL_PASSWORD
              value: dbuser123
            - name: MYSQL_ROOT_PASSWORD
              value: dbuser123
            - name: MYSQL_ROOT_PASSWORD_ENCRYPTED
              value: "false"
            - name: MYSQL_USER
              value: dbuser
          image: mysql:8.0
          name: mysql
          ports:
            - containerPort: 3306
              hostPort: 3309
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-db
      restartPolicy: Always
      volumes:
        - name: mysql-db
          persistentVolumeClaim:
            claimName: mysql-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mysql-db
  name: mysql-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  type: NodePort
  ports:
    - name: "dbport"
      port: 3306
      targetPort: 3306
      # nodePort: 30080 # exposed to host
  selector:
    io.kompose.service: mysql
