name: CI

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ["1.22.x"]
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      # Setup go
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      # Set up node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Node
      - run: npm ci
      - run: npm run install
      - run: npm run lint
      - run: npm run test
      - run: npm run build

  build-image:
    name: build-image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f docker-compose.yml build
